exclude: ^.*/__init__.py$

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        # exlude j2 and json and similar
        exclude: ^.*\.j2$|.*\.json$|.*\.jsonl$|.*\.partial_json$|.*\.xml$|.*\.txt$
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: check-added-large-files
        args: [ "--maxkb=5000" ]
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.13
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/fpgmaas/deptry.git
    rev: 0.23.0
    hooks:
      - id: deptry

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: v1.13.0
    hooks:
      - id: basedpyright
