[project]
name = "GenAI-POC-Template"
version = "0.1.0"
description = "A standardized template for Generative AI applications, promoting best practices and consistency across projects."
authors = [
    { name = "Florian Bindereif" },
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
